### PR TITLE
feat: Append default-filter and unread tag to searches

### PR DESCRIPTION
**Pull request by Thaodan**
Append default filter and unread-status to search filters.

Right now it is done by default but it might make sense to have the option to disable that.

### CODE REVIEW

**Comment by SqrtMinusOne** [comment]
Doesn't the commit https://github.com/SqrtMinusOne/elfeed-summary/commit/125e0f059d9f186efa2a04e317b59245963d6f11 cover that change?

**Comment by Thaodan** [comment]
Korytov Pavel ***@***.***> writes:

> Doesn't the commit
> https://github.com/SqrtMinusOne/elfeed-summary/commit/125e0f059d9f186efa2a04e317b59245963d6f11
> cover that change?

I looks similarly however my change also added the unread tag (format
"+%" unread) depending if toggle-only-unread is there, can you add that?

**Comment by SqrtMinusOne** [comment]
> my change also added the unread tag (format "+%" unread) depending if toggle-only-unread is there

I've implemented the logic I originally indented in that commit:

- if the search has unread entries, add `+unread`
- if invoked with `M-RET`, don't add `+unread` regardless

**Comment by Thaodan** [comment]
Clos

> I've implemented the logic I originally indented in that commit:
> 
>     * if the search has unread entries, add `+unread`
> 
>     * if invoked with `M-RET`, don't add `+unread` regardless

I assume the option to view only queries with unread entries does the same. Closing.

**Pull request closed without merging**
